### ISSUE TITLE
Support non-disruptive serialization of `Network`  

### ISSUE THREAD

**Issue by EronWright** [numenta/htm.java#417] opened 2016-05-01 22:14 UTC
The act of serializing the `Network` causes it to halt because `shouldDoHalt` is true by default.   The ideal would be to not halt the network in `preSerialize`, or to allow `shouldDoHalt` to be set by the user.   

The checkpoint-to-file functionality in HTM.java actually suppresses the halting behavior by briefly setting `shouldDoHalt` to false.   In the flink-htm library, Flink takes care of higher-level checkpointing to a Flink-provided storage backend; we desire to use only the `SerializerCore` interface for flink-htm.

**Comment by cogmission** [comment] 2016-05-01 23:06
The store() operation halts the network before storing, this is by design. The checkpoint() method should be used if halting is not desired.

@EronWright  Please use the methods outlined in the Gist I sent you which use the SerializerCore specifically. You can refer to them here: https://gist.github.com/cogmission/25c4d5935aa0fc6e65ccafd26a4410a8

Unless there is any further concern, I will close this once I get your feedback.

**Comment by EronWright** [comment] 2016-05-01 23:39
@cogmission yep I am using the KryoSerializer from the gist.    Basically I need to serialize the network without halting it.    Flink has some complicated state management code that uses the supplied serializer to checkpoint at a time of its choosing.

I cannot use the checkpoint method, I just need non-destructive serialization.    If `shouldDoHalt` could be set to false, the problem would be solved.  Can you help?

**Comment by cogmission** [comment] 2016-05-01 23:55
Sure... Let me remind myself of what's going on, because I need to see why the KryoSerializer would be using the ```store()``` or ```checkpoint()``` method (it shouldn't). As far as I remember, the KryoSerializer serializes the ```Persistable``` directly? Give me a second to refresh my memory...

**Comment by EronWright** [comment] 2016-05-02 00:13
I've prepared a PR to show how flink-htm will be updated to support 0.6.7 incl. checkpointing functionality.   
https://github.com/nupic-community/flink-htm/pull/15

**Comment by cogmission** [comment] 2016-05-02 00:16
I have a question, since you aren't using Sensors, are you calling ```start()``` on the Network at all? I need to know if you are running the Network in threaded mode?

**Comment by EronWright** [comment] 2016-05-02 00:22
Correct I am not using sensors, and not calling start.

**Comment by cogmission** [comment] 2016-05-02 00:35
If I am correct. ```shouldDoHalt()``` shouldn't have any effect on your code then? Does it present a problem?

**Comment by EronWright** [comment] 2016-05-02 00:43
The issue appears to be that `Network.preSerialize` calls `halt` if `shouldDoHalt` is true.    So I would prefer not to halt the network during serialization.      Note that access to the network instance is synchronized by Flink during checkpointing.

**Comment by cogmission** [comment] 2016-05-02 00:51
Yes but have you tested it? Because ```halt()``` is only germane if you are running the Network in threaded mode? There is nothing being halted if you aren't feeding it data? "halt" refers to the internal operation thread, if that thread isn't running then calling "halt" should be a no-op?

**Comment by EronWright** [comment] 2016-05-02 00:55
Yep this came after some investigation; if I override `shouldDoHalt` then everything seems to work.   The observer between the layer and the algorithm appears to become disconnected during halt.

**Comment by cogmission** [comment] 2016-05-02 00:59
I see. Ok, what I'll do is check for a running thread in addition to checking ```shouldDoHalt```, since I really need to control serialization of the Network in threaded mode, I don't want to circumvent that - but since you aren't using it in threaded mode, I can just check ```shouldDoHalt && isThreadRunning```, should be an easy fix and should avoid calling ```halt()``` in your scenario.

**Comment by cogmission** [comment] 2016-05-02 01:02
I'm going to update the code, and push a new release... stay tuned... ;)

**Comment by EronWright** [comment] 2016-05-02 01:09
@cogmission consider including #418 if you have time before the next release.

**Comment by cogmission** [comment] 2016-05-02 01:37
@EronWright Ok, no problem... I have a question then (please see that issue #418)...

**Comment by cogmission** [comment] 2016-05-02 01:51
#Fixed in https://github.com/numenta/htm.java/pull/419

**Closed** 2016-05-02 10:46 UTC
Labels: api, enhancement, in progress, P2
