### ISSUE TITLE
Parameters.java: defaultTemporalParams(KEY.LEARN) is overwritten by defaultSpatialParams(KEY.LEARN)

### ISSUE THREAD

**Issue by chessweb01** [numenta/htm.java#226] opened 2015-06-10 17:50 UTC
In Parameters.java two maps for default parameters are defined: `defaultSpatialParams` and `defaultTemporalParams`. Later those maps are combined to `defaultParams`. Both temporal and spatial maps allow the definition of a value that is specified by the key `KEY.LEARN`. But only the `defaultSpatialParams` value ends up in the `defaultParams` map because it overwrites the `defaultTemporalParams` value due to identical keys. Is this intentional?

**Comment by cogmission** [comment] 2015-06-10 18:31
Yes. This is so that KEY.LEARN can be applied for SP params and TM params separately if either of those are the base params. If using one Parameters object across all components then that learning value is applied to all components for all Layers configured with those Parameters. To set them separately, you must create (or copy) a set of desired parameters then set the parameter separately **--OR--** You can call Layer.alterParameter() with the new Parameter value and it will copy (in place) the Parameters used in that layer. See the discussion on Parameters from the NAPI Component wiki page for more on this.

I will close this because this is intended behavior...

**Closed by cogmission** 2015-06-10 18:31 UTC
