### ISSUE TITLE
Unable to debug in Eclipse

### ISSUE THREAD

**Issue by pulinagrawal** [numenta/htm.java#205] opened 2015-03-12 02:00 UTC
Hi,

I am now using jdk & jre 8. I am having issues in debugging the code.

The debugger hangs with the following stack trace. 
org.numenta.nupic.examples.sp.RunMNIST at localhost:60517	
	Thread [main] (Suspended (exception ArrayIndexOutOfBoundsException))	
		owns: MethodDescriptor  (id=30)	
		owns: Collections$SynchronizedMap<K,V>  (id=31)	
		SignatureParser.current() line: 95	
		SignatureParser.parseSuperInterfaces() line: 559	
		SignatureParser.parseClassSignature() line: 214	
		SignatureParser.parseClassSig(String) line: 156	
		ClassRepository.parse(String) line: 54	
		ClassRepository.parse(String) line: 41	
		ClassRepository(AbstractRepository<T>).<init>(String, GenericsFactory) line: 74	
		ClassRepository(GenericDeclRepository<S>).<init>(String, GenericsFactory) line: 48	
		ClassRepository.<init>(String, GenericsFactory) line: 50	
		ClassRepository.make(String, GenericsFactory) line: 67	
		ClassRepository.<clinit>() line: 43	
		Class<T>.getGenericInfo() line: 2546	
		Class<T>.getTypeParameters() line: 713	
		TypeResolver.getActualType(Class<?>) line: 372	
		TypeResolver.resolveInClass(Class<?>, Type[]) line: 96	
		FeatureDescriptor.getParameterTypes(Class<?>, Method) line: 387	
		MethodDescriptor.setMethod(Method) line: 116	
		MethodDescriptor.<init>(Method, ParameterDescriptor[]) line: 72	
		MethodDescriptor.<init>(Method) line: 56	
		Introspector.getTargetMethodInfo() line: 1205	
		Introspector.getBeanInfo() line: 426	
		Introspector.getBeanInfo(Class<?>) line: 173	
		Introspector.getBeanInfo(Class<?>, Class<?>, int) line: 260	
		Introspector.<init>(Class<?>, Class<?>, int) line: 407	
		Introspector.getBeanInfo(Class<?>) line: 173	
		BeanUtil.getPropertiesInfoForBean(Class<?>) line: 163	
		BeanUtil.getPropertyInfo(Class<?>, String) line: 141	
		BeanUtil.getPropertyInfo(Object, String) line: 125	
		BeanUtil.setSimpleProperty(Object, String, Object) line: 59	
		Parameters.apply(Object) line: 360	
		RunMNIST.<init>(int[], int[]) line: 95	
		RunMNIST.main(String[]) line: 237	

I tried to resume but it never seems to end. I can never reach the line which I need to debug.

**Comment by cogmission** [comment] 2015-03-12 03:04
Hi Pulin,

What version of Eclipse are you using? (You need Luna). Also, that doesn't
look like a typical Java stack trace - what happens if you right click on
the test directory ".../src/test/java/org/numenta/nupic/research" and then
choose "Run as JUnit Test"? (<-- That may not be the exact phrasing, I'm
not looking at my dev environment right now).

The tests should execute and you should get a green bar indicating all
tests pass.

Try that, and lets see what is going on with your development environment?

Cheers,
David

On Wed, Mar 11, 2015 at 9:00 PM, Pulin Agrawal <notifications@github.com>
wrote:

> Hi,
>
> I am now using jdk & jre 8. I am having issues in debugging the code.
>
> The debugger hangs with the following stack trace.
> org.numenta.nupic.examples.sp.RunMNIST at localhost:60517
>
> Thread main
> <http://Suspended%20(exception%20ArrayIndexOutOfBoundsException)>
>
> owns: MethodDescriptor (id=30)
> owns: Collections$SynchronizedMap (id=31)
> SignatureParser.current() line: 95
>
> SignatureParser.parseSuperInterfaces() line: 559
>
> SignatureParser.parseClassSignature() line: 214
> SignatureParser.parseClassSig(String) line: 156
> ClassRepository.parse(String) line: 54
>
> ClassRepository.parse(String) line: 41
>
> ClassRepository(AbstractRepository).(String, GenericsFactory) line: 74
> ClassRepository(GenericDeclRepository).(String, GenericsFactory) line: 48
>
> ClassRepository.(String, GenericsFactory) line: 50
>
> ClassRepository.make(String, GenericsFactory) line: 67
>
> ClassRepository.() line: 43
> Class.getGenericInfo() line: 2546
>
> Class.getTypeParameters() line: 713
>
> TypeResolver.getActualType(Class<?>) line: 372
>
> TypeResolver.resolveInClass(Class<?>, Type[]) line: 96
>
> FeatureDescriptor.getParameterTypes(Class<?>, Method) line: 387
> MethodDescriptor.setMethod(Method) line: 116
>
> MethodDescriptor.(Method, ParameterDescriptor[]) line: 72
> MethodDescriptor.(Method) line: 56
>
> Introspector.getTargetMethodInfo() line: 1205
>
> Introspector.getBeanInfo() line: 426
>
> Introspector.getBeanInfo(Class<?>) line: 173
>
> Introspector.getBeanInfo(Class<?>, Class<?>, int) line: 260
> Introspector.(Class<?>, Class<?>, int) line: 407
>
> Introspector.getBeanInfo(Class<?>) line: 173
>
> BeanUtil.getPropertiesInfoForBean(Class<?>) line: 163
>
> BeanUtil.getPropertyInfo(Class<?>, String) line: 141
>
> BeanUtil.getPropertyInfo(Object, String) line: 125
>
> BeanUtil.setSimpleProperty(Object, String, Object) line: 59
> Parameters.apply(Object) line: 360
>
> RunMNIST.(int[], int[]) line: 95
>
> RunMNIST.main(String[]) line: 237
>
> I tried to resume but it never seems to end. I can never reach the line
> which I need to debug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/205>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by pulinagrawal** [comment] 2015-03-12 18:58
I am using Luna.
This was the stack that I saw in the debug window. I copied it by right
clicking on the Thread main in the debug window. It looks the same over
there.

All the SpatialPoolerTest and TemporalMemoryTest passed. (46/46)

Pulin Agrawal
पुलिन अग्रवाल

**Comment by cogmission** [comment] 2015-03-12 20:04
The second guess I have is that you somehow have an Exception Breakpoint set, and your code is throwing the ArrayIndexOutOfBoundsException in your stack trace, which is then suspending your  execution thread. The problem with exception break points is that they can be set off by bugs in Eclipse as well as by the user (I've been there before). 

The application tests pass which means the problem is with tour application code. 

This is either your issue or an Eclipse issue and is beyond our purview. However, if you have your own fork I'd be willing to clone it and see if I can't identify the cause of your bug? Closing this issue though...

**Comment by pulinagrawal** [comment] 2015-03-12 21:33
Thank you so much for all your help. I will follow that lead and see if I
can track the problem.

I do have a fork at pulinagrawal/htm.java, and I am working on the
'sandbox' branch. But I don't want to trouble you with this right now. If I
am unable to resolve this, I will then ask you to have a glance. Thanks for
offering your help and information about this Exception Breakpoint bit.

Pulin Agrawal
पुलिन अग्रवाल

**Comment by cogmission** [comment] 2015-03-12 21:57
@pulinagrawal You're very welcome! Let me know how it goes?

**Closed by cogmission** 2015-03-12 21:57 UTC
