### ISSUE TITLE
Modify the QuickTest

### ISSUE THREAD

**Issue by rengelking** [numenta/htm.java#202] opened 2015-03-09 19:18 UTC
Getting me contributing by force!  I do see some small things that could be improved, even with my limited knowledge.

**Comment by cogmission** [comment] 2015-03-09 19:38
Hey Ray can you fill out a description as to what the problem is and give it a little bit more explanation?

**Comment by rengelking** [comment] 2015-03-09 19:55
The first problem was due to my own lack of knowledge/experience.  I was computing the anomaly score for each data sample:
```java
double score = Anomaly.computeRawAnomalyScore(input, predictedColumns);   
```
It needed to be:
```java
double score = Anomaly.computeRawAnomalyScore(input, lastPredicted);
```

The next difficulty, was converting the data from a swarm model I had run on Python, to get the values converted over to their corresponding values in the QuickTest getParameters() and main() ScalarEncoder.builder and CLAClassifier. and I think I have figured all of that out.

A third possible problem is that the ScalarEncoder.Builder builder() .maxVal(), when set to the actual max value of the data, will give an error.  For example, if the max value is 7.0, and that is set as .maxVal(7.0), there is an error:
 input (7.0) greater than periodic range (1.0 - 7.0 ... this could just be due to my not understanding what is going on, as when I set .periodic(false), then I don't get that error... I need to do more research.

**Comment by cogmission** [comment] 2015-03-09 20:00
Could that last one be due to #200? Which is now fixed? Could you try updating and see if you still get the problem?

**Comment by cogmission** [comment] 2015-03-09 20:02
Oh and thanks for the great description!

**Comment by rengelking** [comment] 2015-03-09 20:07
I am not getting the problem described on #200.  My problem was due to my ignorance of how things are supposed to work!

**Comment by rengelking** [comment] 2015-03-09 20:08
When I get some time, I will have to go through that GitHub contributing tutorial as I don't use GitHub that often for projects.

**Comment by cogmission** [comment] 2015-06-09 08:14
@rengelking I think you solved this?  Also this work has now been kinda obsoleted by the inclusion of a Network API - which makes assembling applications that much easier.

**Closed by cogmission** 2015-06-09 08:14 UTC
